addons:
  postgresql: 9.6
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:create
language: ruby
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test