version: 1
update_configs:
  # required properties omitted ...
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
    - match: {dependency_type: "all", update_type: "all"}